accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='detail'),
    url(r'^createpost/$', views.post_new, name='post_new'),
    url(r'^(?P<post_pk>\d+)/commentcreate/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit$', views.comment_edit, name='comment_edit'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^$', lambda request: redirect('/blog/')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'photo', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

accounts/views.py
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.core.urlresolvers import reverse
from django.contrib import messages


# Create your views here.

def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', {'post_list': post_list})

def post_detail(request, pk):
    post_detail = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/detail.html', {'post_detail': post_detail})

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '글이 생성됐습니다.')
            return redirect(reverse('blog:detail', args=[post.pk]))
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})


def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            messages.success(request, '댓글이 생성됐습니다.')
            return redirect(post.get_absolute_url())
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


def comment_edit(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Post, pk=post_pk)
            comment.save()
            messages.success(request, '댓글이 수정되었습니다.')
            return redirect(comment.post.get_absolute_url())
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_form.html', {
        'form': form,
    })

accounts/templates/accounts/signup_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<title>Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
    padding-bottom: 30px;
}
</style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li style="color: white; padding: 15px">{{ user.username }} 님, 환영합니다</li>
              <li><a href="{% url "logout" %}?next={{ request.path }}">로그아웃</a></li>
            {% else %}
              <li><a href="{% url "login" %}?next={{ request.path }}">로그인</a></li>
              <li><a href="{% url "signup" %}">회원가입</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                 {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/blog/comment_form.html
<div class="row">
    <div= class="container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" />
        </form>
    </div>
</div>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="row">
        <h1>{{ post_detail.title }}</h1>
        생성일: {{ post_detail.created_at }}<br>
        수정일: {{ post_detail.updated_at }}<hr/>
        <img src="{{ post_detail.photo.url }}"/><hr/>
        {{ post_detail.content }}<br><hr/>
        <div>
            <h2>덧글</h2>
            <a href="{% url 'blog:comment_new' post_detail.pk %}" class="btn btn-default"> 덧글 생성 </a>
            {% if post_detail.comment_set.all %}
                {% for comment in post_detail.comment_set.all %}
                    <li>
                        {{ comment.message }} <a href="{% url 'blog:comment_edit' post_detail.pk comment.pk %}">수정</a>
                    </li>
                {% endfor %}
            {% else %}
                <h3> 등록된 덧글이 없습니다 </h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="row">
        <a href="{% url 'blog:post_new' %}">글쓰기</a><br>
        {% for post in post_list %}
        <div class="col-sm-4">
            <img src="{{ post.photo.url }}" style="max-width: 100%;" />
            <div class="caption">
                <a href="{% url 'blog:detail' post.id %}">
                    {{ post.title }}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>